import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import MobileMenu from "./components/MobileMenu";
import DesktopNav from "./components/DesktopNav";
import { ThemeProvider } from "./components/ThemeProvider";
import ThemeSwitch from "./components/ThemeSwitch";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems = [
    { name: "Home", href: "/" },
    { name: "Chi siamo", href: "/chi-siamo" },
    { name: "Progetti", href: "/progetti" },
    { name: "Contatti", href: "/contatti" },
    { name: "Newsletter", href: "/newsletter" },
  ];

  return (
    <html lang="it" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <header className="cilto-bg-blue shadow-lg sticky top-0 z-10">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3 flex justify-between items-center">
              {/* Logo e Titolo */}
              <div className="flex items-center space-x-3">
                <div className="w-12 h-12 rounded-full bg-white flex items-center justify-center">
                  <Image
                    src="/progetti/ciltosilogo.jpg"
                    alt="CIL Tosi Logo"
                    width={40}
                    height={40}
                    className="rounded-full"
                  />
                </div>
                <h1 className="text-white text-xl font-bold tracking-tight">
                  CILTOsi
                </h1>
              </div>

              {/* Navigazione e Menu Mobile */}
              <div className="flex items-center">
                  <DesktopNav navItems={navItems} />
                  <MobileMenu navItems={navItems} />
                  <ThemeSwitch />
              </div>
            </div>
          </header>

          <main>{children}</main>

          <footer className="cilto-bg-blue mt-12 py-6">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-sm text-gray-300">
              &copy; 2025 CILTOsi. Powered by Studenti Informatici.
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
